# Generated by Django 4.2.4 on 2023-08-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('time', models.CharField(max_length=80)),
            ],
            options={
                'unique_together': {('time', 'image')},
            },
        ),
    ]
