# Generated by Django 4.2.4 on 2023-08-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='time',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
