# Generated by Django 4.2.4 on 2023-08-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsdata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='time',
            field=models.CharField(max_length=80),
        ),
    ]
