# Generated by Django 4.2.4 on 2023-08-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsdata_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newsdata',
            unique_together={('image', 'time')},
        ),
    ]
